plugins {
    id 'java'
}

group 'fuotaai.hu'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

configurations {
    extraLibs
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.8.1'
    extraLibs group: 'org.apache.commons', name: 'commons-lang3', version: '3.0'

    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
    testImplementation 'org.assertj:assertj-core:3.6.1'

    configurations.implementation.extendsFrom(configurations.extraLibs)
}

test {
    jvmArgs(['--enable-preview'])
}

jar {
    manifest {
        attributes "Main-Class": "typed.ski.deep.SKI"
    }

    from {
        configurations.extraLibs.collect { it.isDirectory() ? it : zipTree(it) }
    }
}

tasks.register('startInREPL', JavaExec) {
    group = "typed ski"
    description = "Runs SKI in REPL mode"

    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'typed.ski.deep.SKI'
    standardInput = System.in
}

test {
    useJUnitPlatform()
}